# Generated by Django 4.0.3 on 2022-03-31 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('second_last_name', models.CharField(max_length=20)),
                ('pos', models.CharField(choices=[('piv', 'Pivot'), ('cie', 'Cierre'), ('a_i', 'Ala_iquierda'), ('a_d', 'Ala_derecha'), ('por', 'Portero'), ('nsp', 'Sin_especificar')], default='nsp', max_length=3)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('teams', models.ManyToManyField(to='champions_app.team')),
            ],
        ),
    ]
